name: Create spreadsheet and configure apps-script

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      spreadsheet_name:
        description: Spreadsheet Name
        type: string
        required: true
      query_identifier:
        type: choice
        description: Query Name
        required: true
        options:
          - b2b-2025
          - b2b-2026
          - d2c-2025
          - d2c-2026
          - kore001-2025
          - kore001-2026
          - lb
          - marketplaces-2025
          - marketplaces-2026
          - Test_Martin

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Print env
        run: env

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        if: github.event_name == 'workflow_dispatch'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          TABLE_NAME: ${{ inputs.query_identifier }}
          SPREADSHEET_NAME: ${{ inputs.spreadsheet_name }}
        run: ./asctl spreadsheet create

      - name: Renew token
        if: github.event_name == 'schedule'
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./asctl token renew