name: Create spreadsheet and configure apps-script

on:
  workflow_dispatch:
    inputs:
      spreadsheet_name:
        description: Spreadsheet Name
        type: string
      query_identifier:
        description: Query Filename (without extension) Example for `lb.csv` it is `lb`
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          TABLE_NAME: ${{ inputs.query_identifier }}
          SPREADSHEET_NAME: ${{ inputs.spreadsheet_name }}
        run: python main.py